# Generated by Django 5.1.3 on 2024-12-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders", through="api.OrderItem", to="api.product"
            ),
        ),
    ]
